apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghost
resources:
  - ../../base/ghost
  - secret-provider-class.yaml
patches:
  - path: ghost-values.yaml
    target:
      kind: HelmRelease
      name: ghost
