apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  values:
    ghost:
      url: "https://ghost.acceptance.local"
      database:
        existingSecret: ghost-db-credentials
    httpRoute:
      hostname: ghost.acceptance.local
