apiVersion: v1
kind: Secret
metadata:
    name: ghost-db-credentials
stringData:
    database-password: ENC[AES256_GCM,data:g96o//XSXDjwLcQSG5EM8UbY/FZeP7T/H3VYi56IoZk=,iv:5y9m0ndtvnhz7tx21SmL/3OfwlmvCy8dvdcFWbvmsXw=,tag:hM6FQad2/uyuYrXOXZjhmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbE40bkl1SnZ5VmMydlA3
            OTB2UFdlK2lKVUxtNWx3Q2Zob3owZjBZK1FnCnVxWlJzVDF0VnNBeE14QTdKQWha
            SUEyRUowc1VvOU0yVGNoZXRObVdkdjQKLS0tIGQ0cmFLSHBnNVpJd0U5S2hEeHZW
            UkRmQWRod01OaUdtWkdiWUJLMWR0SG8Kem3ulJJW01vg+EWRLGVgw17q26ghFhsv
            cognMSDARNrpzLYjYMT+M6OjbPkB8oA/VTG9TdLze0zqz3mcFkOLGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m8969cu3t3kqrcpdfu2g7yp0a6atjvak9xah78696rylapds0sksknuvxl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T22:52:46Z"
    mac: ENC[AES256_GCM,data:ah2UQOSVGMOU1E8CISv+KVh6tNY9aQSVoEsxeAF0T8avlqyFY/IUQfclQZoA6YElXrZ/wPot50Korns8rfMzGNLevjGW7mXVenHC6IDR04Ak9skXyNgMNq5U3eqKgNZUEyvKmqVvm0ffnQ7HmH+XQQ2Vy7J7vgNGVi4CD+FyUWg=,iv:A84W4tE/MEFg3Z5Sis17SkgNz4y384HjaAOhjoK7avI=,tag:Y5Y67+eNedd9llj83WVWYQ==,type:str]
    version: 3.13.3
