apiVersion: v1
kind: Secret
metadata:
    name: slack-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:URGrgHa0hWhcz52pMiBgCrTWWYclWUidwMot9IiSfST301vsToEKsiDRRfB+pFide9Fof2mmMHu0j8jotVu2ra0z02+AOvoCKEX5rw83ooxRcVF7Rvnehhf7NTm2/CQRjjC7aLtqLr3dJRI5BetZ5W8/2ljCF7svrhjMTTI9GYnfPKQ=,iv:tXbNqzbJUZSDhsZXCiQX5cod2dO8gCPqxPurpGp973A=,tag:lTVHe05FCgZtvYgzY5in7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUEhLYll6OGo0RHlhSW5x
            VS9lNE1Vc1M3eStKUWlqTGtJUDJHL3ltL1ZjCjJyWHJiKy9udEpVMTZVa25HN2pt
            YzhvV3RXQ1VLY3cyWDROcFV0TXAvQVkKLS0tIHFBZVRuUG45b1BLdklub1NGSStZ
            ZmRWQThBN0lqTEU5MkpCRTRXTEhIVjQKN5FpcWG4P4vsCkBGvrmOqMQ1CpzSp0qb
            /x5BgADLIyPv6qpbbHkHScjecz24+gcj3XOr13hRxP7yZ6lpeQ+xHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m8969cu3t3kqrcpdfu2g7yp0a6atjvak9xah78696rylapds0sksknuvxl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T11:22:05Z"
    mac: ENC[AES256_GCM,data:/TgSBXpRVJmqQi3wbN2UthMRpOY5EZhnO5giULzjF5Ub5JS0M+PnXH97YEYFQB4IgJxCdQGP+0X8GR/Raz1BgXfAxuQxA6JMb6On9DdTxMt+CKnidv3LQfegZCj4Z1/X2HZ/Pu+ajiKYYjcDJdqBhmVS8CurhHpPxhCPJ83quwI=,iv:dwemv0F7G4HuTcSbUgbDLUbaX5rcT2ObODHK92lvfno=,tag:ori+K3pXvptduUbgcC604w==,type:str]
    version: 3.13.3
