apiVersion: v1
kind: Secret
metadata:
    name: ghost-db-credentials
stringData:
    database-password: ENC[AES256_GCM,data:2yOk00Tk5ddwp2ulLmCnd/39TwIxokXciRX7bnjnwAo=,iv:OgPqqIzi3hNeI5MHiTklv/LefA20Won0aH5AFiR3Pmk=,tag:pBTIlxg4raPt4wf35VG5ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MC9scUJBRDEwQWxKMXoz
            Q0l6d3ZXYTcxaDVBY3pXeEJIYzVDUnpvRjFVCm03RWpYT2xBZGlGMExVanc3Y0RS
            OHV0YjJidVBkOFJZOEdReUJLVTk4ZjQKLS0tIFUycEJ5WXJ6QUNrOW15QjNuQmhD
            TzdBRHBTaGVCdkZYUzdqQXJ5cVJULzAKIDuRUEQpF9GKHTx96ftcmT+7331fvGu4
            ql0OavOOFExZYmMjwTff/+FmXtPlJWa3BZt6tr2YIMEPPxOYh1b8aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m8969cu3t3kqrcpdfu2g7yp0a6atjvak9xah78696rylapds0sksknuvxl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T22:52:46Z"
    mac: ENC[AES256_GCM,data:15UEeGNrer1ZqOBNrP1s4HdpA6oB7bFJWVVG3QmmrU1VLCibgamaW097geDbOPxxQyjZne3Ec9ycpgI63VNsLqXCXUzkgXM9l1VyP+zhp7bu+IuUqSEmXpHSypzVl3pC2mHkIl3ufNtYV83fZboY+f/wAyL7s6O37siR7VI4sE0=,iv:7m1XuYec4PtXtR0PvrCpYH/i6scsdS6eCqGwSKg98HY=,tag:b1HrfpfYjso9QbSySNeiPA==,type:str]
    version: 3.13.3
